name: bld-examples

on: [ push, pull_request, workflow_dispatch ]

jobs:
  run-bld-examples:
    strategy:
      matrix:
        java-version: [ 17, 21, 24 ]
        kotlin-version: [ 1.9.25, 2.1.21, 2.2.20 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Setup Kotlin ${{ matrix.kotlin-version }}
        uses: fwilhe2/setup-kotlin@main
        with:
          version: ${{ matrix.kotlin-version }}

      - name: Download dependencies
        working-directory: examples
        run: ./bld download

      - name: Run tests
        working-directory: examples
        env:
          KOTLIN_VERSION: ${{ matrix.kotlin-version }}
        run: ./bld compile test
