name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

env:
  KOTLIN_HOME: /usr/share/kotlinc

jobs:
  build-bld-project:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 21, 22 ]
        kotlin-version: [ 1.9.24, 2.0.0 ]

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Download dependencies [examples]
        working-directory: examples
        run: ./bld download

      - name: Run tests [examples]
        working-directory: examples
        run: ./bld compile test

      - name: Download dependencies
        run: ./bld download

      - name: Run tests
        run: ./bld compile test
