name: bld-ci

on: [ push, pull_request, workflow_dispatch ]

env:
  KOTLIN_VERSION: 2.2.20

jobs:
  build-bld-project:
    strategy:
      matrix:
        java-version: [ 17, 21, 24 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Setup Kotlin ${{ env.KOTLIN_VERSION }}
        uses: fwilhe2/setup-kotlin@main
        with:
          version: ${{ env.KOTLIN_VERSION }}

      - name: Download dependencies and compile [examples]
        working-directory: examples
        run: ./bld download compile

      - name: Download dependencies
        run: ./bld download

      - name: Compile source code
        run: ./bld compile

      - name: Run tests
        continue-on-error: true
        run: ./bld test

      - name: Run reporter
        if: ${{ failure() }}
        run: ./bld reporter --all
